//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Cliente_MVC_Lizarraga.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HolaMundoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaMundo", ReplyAction="*")]
        WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse HolaMundo(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HolaMundo", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse> HolaMundoAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AdiosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Adios", ReplyAction="*")]
        WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse Adios(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Adios", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse> AdiosAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        double Sumar(double numero1, double numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SumarAsync(double numero1, double numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operaciones", ReplyAction="*")]
        double Operaciones(int tipo, double numero1, double numero2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Operaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<double> OperacionesAsync(int tipo, double numero1, double numero2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TablaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla", ReplyAction="*")]
        WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse Tabla(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Tabla", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse> TablaAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BisiestosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bisiestos", ReplyAction="*")]
        WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse Bisiestos(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Bisiestos", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse> BisiestosAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaMundoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaMundo", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequestBody Body;
        
        public HolaMundoRequest() {
        }
        
        public HolaMundoRequest(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HolaMundoRequestBody {
        
        public HolaMundoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HolaMundoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HolaMundoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponseBody Body;
        
        public HolaMundoResponse() {
        }
        
        public HolaMundoResponse(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HolaMundoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HolaMundoResult;
        
        public HolaMundoResponseBody() {
        }
        
        public HolaMundoResponseBody(string HolaMundoResult) {
            this.HolaMundoResult = HolaMundoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdiosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Adios", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequestBody Body;
        
        public AdiosRequest() {
        }
        
        public AdiosRequest(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AdiosRequestBody {
        
        public AdiosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AdiosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AdiosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponseBody Body;
        
        public AdiosResponse() {
        }
        
        public AdiosResponse(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AdiosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AdiosResult;
        
        public AdiosResponseBody() {
        }
        
        public AdiosResponseBody(string AdiosResult) {
            this.AdiosResult = AdiosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequestBody Body;
        
        public TablaRequest() {
        }
        
        public TablaRequest(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TablaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double numero1;
        
        public TablaRequestBody() {
        }
        
        public TablaRequestBody(double numero1) {
            this.numero1 = numero1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponseBody Body;
        
        public TablaResponse() {
        }
        
        public TablaResponse(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TablaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TablaResult;
        
        public TablaResponseBody() {
        }
        
        public TablaResponseBody(string TablaResult) {
            this.TablaResult = TablaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BisiestosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Bisiestos", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequestBody Body;
        
        public BisiestosRequest() {
        }
        
        public BisiestosRequest(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BisiestosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int añoinicial;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int añofinal;
        
        public BisiestosRequestBody() {
        }
        
        public BisiestosRequestBody(int añoinicial, int añofinal) {
            this.añoinicial = añoinicial;
            this.añofinal = añofinal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BisiestosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BisiestosResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponseBody Body;
        
        public BisiestosResponse() {
        }
        
        public BisiestosResponse(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BisiestosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BisiestosResult;
        
        public BisiestosResponseBody() {
        }
        
        public BisiestosResponseBody(string BisiestosResult) {
            this.BisiestosResult = BisiestosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap>, WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.HolaMundo(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest request) {
            return base.Channel.HolaMundo(request);
        }
        
        public string HolaMundo() {
            WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequestBody();
            WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse retVal = ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).HolaMundo(inValue);
            return retVal.Body.HolaMundoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse> WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.HolaMundoAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest request) {
            return base.Channel.HolaMundoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoResponse> HolaMundoAsync() {
            WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.HolaMundoRequestBody();
            return ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).HolaMundoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.Adios(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest request) {
            return base.Channel.Adios(request);
        }
        
        public string Adios() {
            WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequestBody();
            WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse retVal = ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).Adios(inValue);
            return retVal.Body.AdiosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse> WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.AdiosAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest request) {
            return base.Channel.AdiosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosResponse> AdiosAsync() {
            WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.AdiosRequestBody();
            return ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).AdiosAsync(inValue);
        }
        
        public double Sumar(double numero1, double numero2) {
            return base.Channel.Sumar(numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<double> SumarAsync(double numero1, double numero2) {
            return base.Channel.SumarAsync(numero1, numero2);
        }
        
        public double Operaciones(int tipo, double numero1, double numero2) {
            return base.Channel.Operaciones(tipo, numero1, numero2);
        }
        
        public System.Threading.Tasks.Task<double> OperacionesAsync(int tipo, double numero1, double numero2) {
            return base.Channel.OperacionesAsync(tipo, numero1, numero2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.Tabla(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest request) {
            return base.Channel.Tabla(request);
        }
        
        public string Tabla(double numero1) {
            WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequestBody();
            inValue.Body.numero1 = numero1;
            WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse retVal = ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).Tabla(inValue);
            return retVal.Body.TablaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse> WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.TablaAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest request) {
            return base.Channel.TablaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.TablaResponse> TablaAsync(double numero1) {
            WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.TablaRequestBody();
            inValue.Body.numero1 = numero1;
            return ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).TablaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.Bisiestos(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest request) {
            return base.Channel.Bisiestos(request);
        }
        
        public string Bisiestos(int añoinicial, int añofinal) {
            WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequestBody();
            inValue.Body.añoinicial = añoinicial;
            inValue.Body.añofinal = añofinal;
            WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse retVal = ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).Bisiestos(inValue);
            return retVal.Body.BisiestosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse> WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap.BisiestosAsync(WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest request) {
            return base.Channel.BisiestosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosResponse> BisiestosAsync(int añoinicial, int añofinal) {
            WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest inValue = new WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequest();
            inValue.Body = new WS_Cliente_MVC_Lizarraga.ServiceReference.BisiestosRequestBody();
            inValue.Body.añoinicial = añoinicial;
            inValue.Body.añofinal = añofinal;
            return ((WS_Cliente_MVC_Lizarraga.ServiceReference.WebServiceSoap)(this)).BisiestosAsync(inValue);
        }
    }
}
